
criação_de_ações_e_objetivos_de_aprendizagem:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Executar as seguintes tarefas:
    1.	Análise dos Dados do Colaborador:
    •	Examinar informações sobre a área de atuação, responsabilidades, métricas de performance, desafios, pontos fortes e objetivos profissionais.
    •	Identificar lacunas de habilidades e áreas prioritárias de desenvolvimento.
    2.	Criação de Ações de Aprendizagem:
    •	Propor ideias criativas para ações educativas que atendam às necessidades do colaborador, incluindo:
    •	Cursos e treinamentos específicos (online, presenciais ou híbridos).
    •	Workshops interativos voltados para situações práticas e desafios reais.
    •	Programas de mentoria com profissionais experientes na área do colaborador.
    •	Projetos aplicados para desenvolver competências em um contexto real.
    •	Estudo autodirigido com curadoria de materiais relevantes (e-books, podcasts, artigos, etc.).
    •	Participação em comunidades ou eventos da área (congressos, meetups, hackathons).
    •	Soft skills coaching para aprimoramento de habilidades interpessoais, como liderança e comunicação.
    3.	Definição de Objetivos de Aprendizagem:
    •	Estabelecer metas claras e mensuráveis para cada ação educativa, por exemplo:
    •	Hard skills: “Aprimorar o uso de [ferramenta] para reduzir o tempo de execução de tarefas em X%”.
    •	Soft skills: “Desenvolver maior assertividade em reuniões, com feedback positivo de colegas em até três meses.”
    •	Priorizar objetivos que tragam impacto direto na performance e no alcance dos objetivos do colaborador.
    4.	Personalização de Propostas:
    •	Adaptar cada ação e objetivo às características do colaborador (nível de senioridade, estilo de aprendizado, disponibilidade de tempo).
    •	Considerar desafios específicos do contexto de trabalho do colaborador.
    5.	Estruturação do Relatório:
    •	Organizar as ideias de forma clara e categorizada, incluindo:
    •	Resumo das necessidades e áreas de foco.
    •	Lista detalhada de ações de aprendizagem propostas.
    •	Objetivos de aprendizagem associados a cada ação.
    •	Recursos necessários e cronograma sugerido.

  expected_output: >
    Um relatório abrangente contendo:
    •	Diagnóstico das necessidades e prioridades de desenvolvimento do colaborador.
    •	Conjunto criativo de ações educativas alinhadas aos objetivos e desafios individuais.
    •	Objetivos de aprendizagem claros e mensuráveis.
    •	Sugestões de recursos e cronograma de implementação.
    •	Propostas organizadas de forma personalizada, prática e com potencial de impacto direto na performance.

report_overview:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Elabore um relatório detalhado que:
    1. Analise o perfil profissional atual
    2. Identifique:
       - Padrões de comportamento que devem ser ajustados
       - Áreas de excelência que devem ser mantidas e exploradas
       - Oportunidades de melhoria baseadas em decisões estratégicas
    3. Crie recomendações personalizadas para desenvolvimento profissional
    4. Sugira próximos passos concretos alinhados com os objetivos do profissional

  expected_output: >
   Um relatório detalhado e estruturado que inclua:
   - **Seções principais de análise:**  
     - Identificação de pontos fortes e fracos.  
     - Sugestões personalizadas para melhoria.  
     - Referências claras às métricas analisadas e ao embasamento teórico do livro de poker.  
   - **Propostas práticas e acionáveis:**  
     - Sugestões para ações imediatas que melhorem a performance.  
     - Estratégias teóricas adaptadas ao estilo e dados do jogador.  
   - **Clareza e personalização:**  
     - Relatório claro, objetivo e com orientações diretamente aplicáveis à rotina do jogador.  
   - **Tabelas e gráficos opcionais:** Para ilustrar tendências e facilitar a compreensão dos dados apresentados.
    O relatório deverá ser um guia prático e estratégico para que o jogador entenda claramente o que precisa fazer para se transformar em um jogador de poker mais eficiente, inteligente e lucrativo.

planejamento_estruturado_de_desenvolvimento_individual:

  description: >
    transformar o relatório de ações educativas e objetivos de aprendizagem em um Plano de Desenvolvimento
     Individual (PDI) estruturado para um período de 1 ano. A tarefa inclui organizar as ações em uma sequência lógica, 
     distribuí-las ao longo de 12 meses e documentá-las em um formato que permita fácil acompanhamento pelo colaborador. 
     O PDI final deve conter uma tabela em markdown com descrições claras e etapas organizadas.
  expected_output: >
    	•	Plano de Desenvolvimento Individual (PDI) com:
    •	Tabela em Markdown, contendo:
    •	Divisão trimestral e mensal das ações.
    •	Descrição clara de cada ação/objetivo.
    •	Resultados esperados e recursos necessários.
    •	Metas trimestrais bem definidas para facilitar o acompanhamento.
    •	Estrutura equilibrada e personalizada, permitindo que o colaborador entenda exatamente o que deve ser 
    feito ao longo do ano e como acompanhar seu progresso.˜
generate_final_summary:

  description: >
    Criar um sumário executivo em formato markdown que sintetize as principais 
    informações geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara e objetiva 
    em uma página, facilitando o entendimento rápido do plano de desenvolvimento e direcionando o 
    colaborador para os documentos mais detalhados.

  expected_output: > 

    Um sumário executivo em markdown que sintetize as principais informações 
    geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara 
    e objetiva em uma página, facilitando o entendimento rápido do plano de desenvolvimento 
    e direcionando o colaborador para os documentos mais detalhados. A formatação em markdown
    não precisa ser indicada, já temos um interpretador de markdown pronto.