generate_metrics_summary:
  description: >
    1.	Inicie a conversa buscando compreender a função, cargo e nível de senioridade do usuário.
    2.	Pergunte sobre suas especializações e principais competências técnicas (hard skills) e interpessoais (soft skills).
    3.	Explore áreas de melhoria percebidas, tanto em habilidades técnicas quanto comportamentais.
    4.	Investigue as principais dificuldades enfrentadas no dia a dia do trabalho, buscando exemplos concretos.
    5.	Pergunte sobre os sentimentos do usuário em relação ao trabalho atual, incluindo motivação, satisfação e frustrações.
    6.	Identifique os objetivos profissionais do usuário e áreas de interesse para desenvolvimento futuro.
    7.	Certifique-se de adaptar as perguntas ao longo da entrevista com base nas respostas dadas pelo usuário.
    8.	Finalize a entrevista garantindo que todas as informações relevantes foram coletadas e organizadas.
    9.	Valide os dados com o usuário, confirmando a precisão das informações e se ele gostaria de adicionar algo.
    10.	Prepare os dados coletados para análise posterior, organizando-os de forma clara e objetiva.

  expected_output: >
    Um conjunto de dados completos e validados prontas para serem utilizados na análise detalhada pela ferramenta “interview_tool”, que incluam:
    •	Função, cargo e nível de senioridade.
    •	Especializações e competências (hard skills e soft skills).
    •	Áreas de dificuldade no trabalho e exemplos de situações enfrentadas.
    •	Sentimentos sobre o trabalho atual, incluindo motivação e frustrações.
    •	Objetivos profissionais e áreas de interesse para desenvolvimento.

create_performance_report:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Elabore um relatório detalhado que:
    1. Analise o perfil profissional atual
    2. Identifique:
       - Padrões de comportamento que devem ser ajustados
       - Áreas de excelência que devem ser mantidas e exploradas
       - Oportunidades de melhoria baseadas em decisões estratégicas
    3. Crie recomendações personalizadas para desenvolvimento profissional
    4. Sugira próximos passos concretos alinhados com os objetivos do profissional

  expected_output: >
   Um relatório detalhado e estruturado que inclua:
   - **Seções principais de análise:**  
     - Identificação de pontos fortes e fracos.  
     - Sugestões personalizadas para melhoria.  
     - Referências claras às métricas analisadas e ao embasamento teórico do livro de poker.  
   - **Propostas práticas e acionáveis:**  
     - Sugestões para ações imediatas que melhorem a performance.  
     - Estratégias teóricas adaptadas ao estilo e dados do jogador.  
   - **Clareza e personalização:**  
     - Relatório claro, objetivo e com orientações diretamente aplicáveis à rotina do jogador.  
   - **Tabelas e gráficos opcionais:** Para ilustrar tendências e facilitar a compreensão dos dados apresentados.
    O relatório deverá ser um guia prático e estratégico para que o jogador entenda claramente o que precisa fazer para se transformar em um jogador de poker mais eficiente, inteligente e lucrativo.

prepare_educational_content:

  description: >
    1. Receber o relatório detalhado criado pelo Especialista em Estratégia e Performance de Poker, que já contém análises completas sobre a performance do jogador, incluindo áreas de melhoria, forças e oportunidades.  
    2. Consultar um renomado livro de poker (disponível em formato PDF na base de conhecimento) para fundamentar o plano de estudo com as melhores práticas, estratégias e conteúdos teóricos.  
    3. Criar um plano de estudo totalmente personalizado, com:  
        - **Conteúdos prioritários:** O que o jogador deve aprender para corrigir falhas (ex.: leitura de ranges, estratégia de blinds, ou quando NÃO fazer aquele blefe heroico).  
        - **Reforço de acertos:** Áreas em que o jogador já é bom, mas pode se tornar excelente (ou seja, consolidar aquela habilidade que faz ele parecer um profissional nas mesas).  
        - **Novos horizontes:** Conteúdos que o jogador talvez nem saiba que precisa, mas que vão transformá-lo na versão "next-level" de si mesmo.  
    4. Garantir que o plano seja claro, progressivo e estruturado com toques de humor para manter o jogador motivado durante o aprendizado. Afinal, poker é coisa séria, mas aprender não precisa ser tão tenso quanto estar "all-in" com um par baixo.  

  expected_output: >
    Um documento de plano de estudo que:  
    - Contenha uma lista personalizada e organizada de tópicos teóricos e práticos que o jogador deve estudar.  
    - Inclua referências diretas ao livro de poker consultado, conectando o aprendizado teórico à prática diária do jogador.  
    - Ofereça sugestões de exercícios ou simulações que ajudem o jogador a internalizar os conceitos.  
    - Apresente as recomendações com um toque de leveza e bom humor, mantendo o jogador engajado e confiante de que está no caminho para dominar as mesas.  
    - Seja um guia prático e motivador, que faça o jogador sentir que aprender poker é tão divertido quanto ganhar um pote gigante (sem ter que mostrar as cartas!).  
    Ao final, o jogador terá um plano que é como um "GPS do poker" – com ele, chegar ao destino de ser um jogador lucrativo e imbatível será só questão de tempo (e algumas boas leituras entre as sessões).

generate_final_summary:

  description: >
    1. Receber os relatórios e análises criados pelos agentes anteriores:  
        - **Analista Estratégico de Métricas de Poker**  
        - **Especialista em Estratégia e Performance de Poker**  
        - **Professor de Poker**  
    2. Revisar todo o conteúdo fornecido para identificar as informações mais importantes e relevantes.  
    3. Condensar as análises e recomendações em um sumário executivo claro, objetivo e impactante.  
    4. Garantir que o documento apresente de forma sucinta:  
        - A visão geral da performance do jogador.  
        - Os pontos fortes e fracos destacados pelos especialistas.  
        - As recomendações principais para melhoria e os próximos passos sugeridos.  
    5. Não realizar novas análises ou interpretações – a tarefa é reproduzir de forma sintética as informações fornecidas pelos agentes, priorizando clareza e organização.
  
  expected_output: > 

    Um **sumário executivo** da performance do jogador, contendo:  
    - **Seção 1: Panorama Geral**  
      - Breve descrição do desempenho atual do jogador, destacando suas métricas mais relevantes.  
    - **Seção 2: Pontos Fortes e Fracos**  
      - Lista objetiva das principais forças e fraquezas identificadas nos relatórios.  
    - **Seção 3: Recomendações e Próximos Passos**  
      - Resumo das ações sugeridas para que o jogador evolua, incluindo:  
        - O que melhorar.  
        - O que reforçar.  
        - O que começar ou deixar de fazer.  
    - **Seção 4: Conclusão Motivacional**  
      - Um parágrafo final que inspire o jogador a colocar as recomendações em prática, destacando o potencial de crescimento e evolução no jogo.  

    O sumário deve ser direto ao ponto, com linguagem acessível e motivadora, funcionando como um guia prático que o jogador pode consultar rapidamente para lembrar suas metas e próximas ações. Em suma, é a versão "cafeína concentrada" de todo o trabalho dos especialistas anteriores.
