analise_subjetiva_colaborador:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Executar uma análise aprofundada do perfil do colaborador:

    1. Análise do Contexto Profissional:
    • Examinar detalhadamente a área de atuação e responsabilidades atuais
    • Avaliar o nível de senioridade e escopo de influência
    • Identificar os principais desafios e complexidades da função

    2. Avaliação de Performance:
    • Analisar as métricas de performance apresentadas
    • Identificar padrões de sucesso e áreas de dificuldade
    • Avaliar a evolução do desempenho ao longo do tempo

    3. Mapeamento de Competências:
    • Identificar pontos fortes e diferenciais do colaborador
    • Mapear gaps de habilidades técnicas e comportamentais
    • Avaliar o nível de maturidade em diferentes competências

    4. Análise de Aspirações:
    • Compreender os objetivos de carreira de curto e longo prazo
    • Identificar motivadores e interesses profissionais
    • Avaliar o alinhamento entre aspirações e perfil atual

    5. Diagnóstico de Necessidades:
    • Priorizar áreas críticas para desenvolvimento
    • Identificar oportunidades de crescimento
    • Avaliar barreiras potenciais para o desenvolvimento

    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" , ou pelo seu própio nome, em suas respostas.

  expected_output: >
    Um relatório analítico detalhado contendo:

    1. Perfil Profissional:
    • Resumo do contexto atual e trajetória
    • Análise das responsabilidades e impacto
    • Avaliação do nível de senioridade e maturidade

    2. Análise de Performance:
    • Interpretação das métricas apresentadas
    • Identificação de padrões e tendências
    • Avaliação de pontos fortes e áreas de melhoria

    3. Mapa de Competências:
    • Detalhamento dos pontos fortes identificados
    • Análise dos gaps de competências
    • Avaliação do nível de maturidade em diferentes áreas

    4. Aspirações e Objetivos:
    • Síntese dos objetivos de carreira
    • Análise dos motivadores e interesses
    • Avaliação do alinhamento com o perfil atual

    5. Recomendações de Desenvolvimento:
    • Priorização das áreas de desenvolvimento
    • Identificação de oportunidades de crescimento
    • Sugestões para superar barreiras identificadas

report_overview:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Elabore um relatório detalhado que:
    1. Analise o perfil profissional atual
    2. Identifique:
       - Padrões de comportamento que devem ser ajustados
       - Áreas de excelência que devem ser mantidas e exploradas
       - Oportunidades de melhoria baseadas em decisões estratégicas
    3. Crie recomendações personalizadas para desenvolvimento profissional
    4. Sugira próximos passos concretos alinhados com os objetivos do profissional

    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" , ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    IMPORTANTE: A formatação em markdown não precisa ser indicada, já temos um interpretador de markdown pronto. Não comece o seu resultado com '```markdown' ou algo do tipo pois isso prejudica nossa ferramenta.

    Um relatório detalhado e estruturado que inclua:
    - **Seções principais de análise:**  
     - Identificação de pontos fortes e fracos.  
     - Sugestões personalizadas para melhoria.  
     - Referências claras às métricas analisadas e ao embasamento teórico do livro de poker.  
    - **Propostas práticas e acionáveis:**  
     - Sugestões para ações imediatas que melhorem a performance.  
     - Estratégias teóricas adaptadas ao estilo e dados do jogador.  
    - **Clareza e personalização:**  
     - Relatório claro, objetivo e com orientações diretamente aplicáveis à rotina do jogador.  
    - **Tabelas e gráficos opcionais:** Para ilustrar tendências e facilitar a compreensão dos dados apresentados.
    O relatório deverá ser um guia prático e estratégico para que o jogador entenda claramente o que precisa fazer para se transformar em um jogador de poker mais eficiente, inteligente e lucrativo.

planejamento_estruturado_de_desenvolvimento_individual:
  description: >
    Com base na análise do perfil do colaborador e nas recomendações de conteúdo fornecidas,
    criar um Plano de Desenvolvimento Individual (PDI) estruturado para 12 meses que:

    1. Integre Informações:
    • Utilize a análise do perfil profissional para entender o contexto e necessidades
    • Considere as recomendações de conteúdo e sua priorização
    • Alinhe o plano com os objetivos de carreira identificados

    2. Estruture a Jornada de Aprendizagem:
    • Organize os conteúdos em uma sequência lógica de desenvolvimento
    • Distribua as atividades ao longo dos 12 meses de forma equilibrada
    • Considere a complexidade e interdependência entre os conteúdos
    • Estabeleça marcos de progresso claros e mensuráveis

    3. Defina Elementos de Acompanhamento:
    • Crie indicadores de progresso para cada trimestre
    • Estabeleça pontos de verificação e revisão
    • Defina critérios claros de conclusão para cada etapa

    4. Documente o Plano:
    • Utilize formato tabular em markdown para fácil visualização
    • Inclua descrições claras e objetivas das atividades
    • Forneça orientações práticas para execução

    Para você criar o plano de desenvolvimento individual, você deve utilizar exclusivamente as informações fornecidas na análise do perfil do colaborador e nas recomendações de conteúdo fornecidas

    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" , ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    IMPORTANTE: A formatação em markdown não precisa ser indicada, já temos um interpretador de markdown pronto. Não comece o seu resultado com '```markdown' ou algo do tipo pois isso prejudica nossa ferramenta.

    Um Plano de Desenvolvimento Individual (PDI) completo contendo:

    1. Visão Geral:
    • Resumo do perfil e objetivos do colaborador
    • Principais áreas de desenvolvimento identificadas
    • Resultados esperados ao final dos 12 meses

    2. Plano Estruturado (em formato tabular markdown):
    • Divisão por trimestres e meses
    • Para cada período:
      - Conteúdos e atividades programadas com os links para os respectivos materiais quando aplicável
      - Objetivos específicos de aprendizagem
      - Resultados esperados
      - Recursos necessários
      - Indicadores de progresso

    3. Marcos e Acompanhamento:
    • Metas trimestrais detalhadas
    • Critérios de avaliação de progresso
    • Pontos de verificação e ajuste
    
    4. Orientações de Execução:
    • Recomendações práticas para gestão do tempo
    • Estratégias para maximizar o aprendizado
    • Dicas para superar possíveis obstáculos

  agent: pdi_specialist

  context: [
    "analise_subjetiva_colaborador",
    "recomendacao_conteudos",
    "aggregate_and_structure_research"
  ]

ler_planilha:
  description: >
    Utilize a tool 'read_educational_db' para ler e retornar o conteúdo completo 
    da planilha de conteúdos educacionais disponíveis.
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" , ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    Uma lista estruturada de todos os conteúdos educacionais disponíveis, incluindo 
    nome, tipo, área do conhecimento, nível e descrição de cada item.

generate_final_summary:

  description: >
    Criar um sumário executivo em formato markdown que sintetize as principais 
    informações geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara e objetiva 
    em uma página, facilitando o entendimento rápido do plano de desenvolvimento e direcionando o 
    colaborador para os documentos mais detalhados.
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" em suas respostas.

  expected_output: > 
    IMPORTANTE: A formatação em markdown não precisa ser indicada, já temos um interpretador de markdown pronto. Não comece o seu resultado com '```markdown' ou algo do tipo pois isso prejudica nossa ferramenta.

    Um sumário executivo em markdown que sintetize as principais informações 
    geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara 
    e objetiva em uma página, facilitando o entendimento rápido do plano de desenvolvimento 
    e direcionando o colaborador para os documentos mais detalhados. 

recomendacao_conteudos:
  description: >
    Com base nas informações coletadas durante a entrevista: {interview_data}
    
    E utilizando os conteúdos disponíveis no catálogo fornecido pelo leitor_de_planilha,
    analise cuidadosamente e selecione os conteúdos mais adequados para o desenvolvimento
    do colaborador.
    
    Para cada conteúdo selecionado, você deve:
    1. Explicar por que esse conteúdo específico é relevante para o colaborador
    2. Relacionar o conteúdo com as necessidades, objetivos ou gaps identificados na entrevista
    3. Sugerir uma ordem de prioridade para consumo dos conteúdos
    4. Indicar como o conteúdo se alinha com os objetivos de desenvolvimento do colaborador
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você", ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    IMPORTANTE: A formatação em markdown não precisa ser indicada, já temos um interpretador de markdown pronto. Não comece o seu resultado com '```markdown' ou algo do tipo pois isso prejudica nossa ferramenta.

    Um relatório detalhado contendo:
    
    1. Lista dos conteúdos recomendados, cada um com:
       - Nome e tipo do conteúdo
       - Justificativa detalhada da escolha
       - Relação com as necessidades identificadas
       - Prioridade sugerida
       - Benefícios esperados
    
    2. Plano de sequenciamento:
       - Ordem sugerida para consumo dos conteúdos
       - Justificativa para a sequência proposta
    
    3. Alinhamento estratégico:
       - Como os conteúdos selecionados contribuem para os objetivos de desenvolvimento
       - Resultados esperados após a conclusão dos conteúdos

technical_skills_research:
  description: >
    Conduza uma pesquisa para identificar conteúdos relacionados às competências técnicas
    específicas mencionadas durante a entrevista do colaborador. Inclua cursos online,
    artigos técnicos, livros recomendados e blogs de especialistas, vídeos do youtube.

    ## Resumo da entrevista:

    {interview_data}
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você", ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    Uma lista de 10 conteúdos técnicos, incluindo títulos, autores, tipo de conteúdo e links, com uma
    breve descrição sobre como esses recursos podem ajudar no desenvolvimento técnico
    do colaborador.

behavioral_skills_research:
  description: >
    Pesquise por conteúdos relacionados às competências comportamentais e soft skills mencionadas
    na entrevista, como liderança, comunicação, resolução de conflitos ou outras habilidades
    interpessoais. Busque exemplos práticos, como estudos de caso ou workshops.

    ## Resumo da entrevista:

    {interview_data}
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você", ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    Uma lista de 10 recursos focados em desenvolvimento comportamental, com links, descrições dos links, autores, tipo de conteúdo e
    um parágrafo sobre como os conteúdos se aplicam às necessidades do colaborador. 

industry_trends_and_inspiration_research:
  description: >
    Realize uma pesquisa sobre tendências emergentes na indústria do colaborador e materiais
    inspiracionais que ajudem a alinhar seu desenvolvimento com as direções futuras do setor.
    Inclua podcasts, artigos, vídeos de palestras e discussões em fóruns.

    ## Resumo da entrevista:

    {interview_data}
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você" , ou pelo seu própio nome,em suas respostas.

  expected_output: > 
    Uma lista de 10 recursos que conectem o colaborador às tendências da indústria e insights
    inspiradores, com explicações sobre sua relevância para o desenvolvimento do colaborador, links, descrições dos links, autores e tipo de conteúdo.

aggregate_and_structure_research:
  description: >
    Analise os resultados das três pesquisas anteriores: competências técnicas,
    competências comportamentais e tendências/inspiração da indústria. 
    Selecione os melhores recursos de cada pesquisa com base em relevância, qualidade,
    aplicabilidade e variedade. Estruture o conteúdo consolidado em uma lista 
    organizada por categoria, pronta para ser utilizada no desenvolvimento do PDI.
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você", ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    Um documento estruturado com:
    - Categorias: Competências Técnicas, Competências Comportamentais, e Tendências/Inspiração.
    - Para cada categoria, até 5 conteúdos selecionados com título, autor, link 
      e uma breve justificativa da escolha.
    - Formatação clara para facilitar o uso por agentes subsequentes.

research_quality_evaluation:
  description: >
    Analise criticamente os resultados das três pesquisas realizadas (técnica, comportamental e tendências)
    e avalie sua adequação às necessidades do colaborador.
    
    Contexto da entrevista do colaborador:
    {interview_data}
    
    Para cada tipo de pesquisa, avalie:
    1. Relevância dos conteúdos encontrados
    2. Adequação ao nível de experiência do colaborador
    3. Alinhamento com os objetivos de desenvolvimento
    4. Qualidade e credibilidade das fontes
    5. Variedade dos formatos de conteúdo
    
    Forneça uma avaliação detalhada para cada tipo de pesquisa e recomendações de melhorias 
    quando necessário.
    Importante: Use sempre linguagem direta e pessoal, tratando o colaborador como "você", ou pelo seu própio nome, em suas respostas.

  expected_output: > 
    Um relatório de avaliação estruturado contendo:
    - Análise individual de cada tipo de pesquisa
    - Pontos fortes e pontos de melhoria
    - Recomendações específicas para aprimoramento
    - Avaliação geral da adequação dos conteúdos

gerar_visualizacao_pdi:
  description: >
    Com base no PDI estruturado anteriormente gerado e que foi enviado a você, criar uma estrutura JSON 
    que represente TODAS as atividades e seus relacionamentos para visualização.

    IMPORTANTE:
    1. Extrair do documento PDI:
       - Todas as atividades educacionais
       - Links e recursos associados
       - Organização trimestral

    2. Garantir que:
       - Todos os links sejam mantidos exatamente como estão no PDI
       - A organização trimestral seja preservada
       - As datas de início/fim sejam convertidas para o formato correto

    3. Validar:
       - Todos os IDs sejam únicos
       - Todos os links estejam presentes para atividades que tenham um link
       - Todas as atividades tenham um trimestre definido


  expected_output: >
    Um arquivo JSON em output/pdi.json seguindo o modelo PDIConfig:
    {
      "titulo": "Plano de Desenvolvimento Individual",
      "subtitulo": "string, opcional",
      "colaborador": "string",
      "periodo": "2025",
      "atividades": [
        {
          "id": "string único",
          "titulo": "string",
          "descricao": "string",
          "trimestre": "inteiro de 1 a 4",
          "tipo": "enum: curso, mentoria, projeto, workshop, leitura, outro",
          "link": "URL do PDI", // opcional já que existem atividades que não possuem link
          "plataforma": "string", opcional 
          "data_inicio": "datetime, opcional",
          "data_fim": "datetime, opcional",
          "tags": ["string", "string", ...], // opcional
          "prerequisitos": ["id_atividade1", "id_atividade2", ...] // opcional
        }
      ]
    }

    IMPORTANTE: 
    - O JSON deve ser válido e seguir exatamente a estrutura do modelo PDIConfig
    - Manter todos os links exatamente como estão no PDI
    - Os IDs das atividades devem ser únicos
    - As datas devem estar em formato ISO 8601

  agent: pdi_specialist

  context: [
    "planejamento_estruturado_de_desenvolvimento_individual"
  ]
