
criação_de_ações_e_objetivos_de_aprendizagem:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Executar as seguintes tarefas:
    1.	Análise dos Dados do Colaborador:
    •	Examinar informações sobre a área de atuação, responsabilidades, métricas de performance, desafios, pontos fortes e objetivos profissionais.
    •	Identificar lacunas de habilidades e áreas prioritárias de desenvolvimento.
    2.	Criação de Ações de Aprendizagem:
    •	Propor ideias criativas para ações educativas que atendam às necessidades do colaborador, incluindo:
    •	Cursos e treinamentos específicos (online, presenciais ou híbridos).
    •	Workshops interativos voltados para situações práticas e desafios reais.
    •	Programas de mentoria com profissionais experientes na área do colaborador.
    •	Projetos aplicados para desenvolver competências em um contexto real.
    •	Estudo autodirigido com curadoria de materiais relevantes (e-books, podcasts, artigos, etc.).
    •	Participação em comunidades ou eventos da área (congressos, meetups, hackathons).
    •	Soft skills coaching para aprimoramento de habilidades interpessoais, como liderança e comunicação.
    3.	Definição de Objetivos de Aprendizagem:
    •	Estabelecer metas claras e mensuráveis para cada ação educativa, por exemplo:
    •	Hard skills: “Aprimorar o uso de [ferramenta] para reduzir o tempo de execução de tarefas em X%”.
    •	Soft skills: “Desenvolver maior assertividade em reuniões, com feedback positivo de colegas em até três meses.”
    •	Priorizar objetivos que tragam impacto direto na performance e no alcance dos objetivos do colaborador.
    4.	Personalização de Propostas:
    •	Adaptar cada ação e objetivo às características do colaborador (nível de senioridade, estilo de aprendizado, disponibilidade de tempo).
    •	Considerar desafios específicos do contexto de trabalho do colaborador.
    5.	Estruturação do Relatório:
    •	Organizar as ideias de forma clara e categorizada, incluindo:
    •	Resumo das necessidades e áreas de foco.
    •	Lista detalhada de ações de aprendizagem propostas.
    •	Objetivos de aprendizagem associados a cada ação.
    •	Recursos necessários e cronograma sugerido.

  expected_output: >
    Um relatório abrangente contendo:
    •	Diagnóstico das necessidades e prioridades de desenvolvimento do colaborador.
    •	Conjunto criativo de ações educativas alinhadas aos objetivos e desafios individuais.
    •	Objetivos de aprendizagem claros e mensuráveis.
    •	Sugestões de recursos e cronograma de implementação.
    •	Propostas organizadas de forma personalizada, prática e com potencial de impacto direto na performance.

report_overview:
  description: >
    Com base nas informações coletadas durante a entrevista:

    {interview_data}

    Elabore um relatório detalhado que:
    1. Analise o perfil profissional atual
    2. Identifique:
       - Padrões de comportamento que devem ser ajustados
       - Áreas de excelência que devem ser mantidas e exploradas
       - Oportunidades de melhoria baseadas em decisões estratégicas
    3. Crie recomendações personalizadas para desenvolvimento profissional
    4. Sugira próximos passos concretos alinhados com os objetivos do profissional

  expected_output: >
   Um relatório detalhado e estruturado que inclua:
   - **Seções principais de análise:**  
     - Identificação de pontos fortes e fracos.  
     - Sugestões personalizadas para melhoria.  
     - Referências claras às métricas analisadas e ao embasamento teórico do livro de poker.  
   - **Propostas práticas e acionáveis:**  
     - Sugestões para ações imediatas que melhorem a performance.  
     - Estratégias teóricas adaptadas ao estilo e dados do jogador.  
   - **Clareza e personalização:**  
     - Relatório claro, objetivo e com orientações diretamente aplicáveis à rotina do jogador.  
   - **Tabelas e gráficos opcionais:** Para ilustrar tendências e facilitar a compreensão dos dados apresentados.
    O relatório deverá ser um guia prático e estratégico para que o jogador entenda claramente o que precisa fazer para se transformar em um jogador de poker mais eficiente, inteligente e lucrativo.

planejamento_estruturado_de_desenvolvimento_individual:

  description: >
    1. Receber o relatório detalhado criado pelo Especialista em Estratégia e Performance de Poker, que já contém análises completas sobre a performance do jogador, incluindo áreas de melhoria, forças e oportunidades.  
    2. Consultar um renomado livro de poker (disponível em formato PDF na base de conhecimento) para fundamentar o plano de estudo com as melhores práticas, estratégias e conteúdos teóricos.  
    3. Criar um plano de estudo totalmente personalizado, com:  
        - **Conteúdos prioritários:** O que o jogador deve aprender para corrigir falhas (ex.: leitura de ranges, estratégia de blinds, ou quando NÃO fazer aquele blefe heroico).  
        - **Reforço de acertos:** Áreas em que o jogador já é bom, mas pode se tornar excelente (ou seja, consolidar aquela habilidade que faz ele parecer um profissional nas mesas).  
        - **Novos horizontes:** Conteúdos que o jogador talvez nem saiba que precisa, mas que vão transformá-lo na versão "next-level" de si mesmo.  
    4. Garantir que o plano seja claro, progressivo e estruturado com toques de humor para manter o jogador motivado durante o aprendizado. Afinal, poker é coisa séria, mas aprender não precisa ser tão tenso quanto estar "all-in" com um par baixo.  

  expected_output: >
    Um documento de plano de estudo que:  
    - Contenha uma lista personalizada e organizada de tópicos teóricos e práticos que o jogador deve estudar.  
    - Inclua referências diretas ao livro de poker consultado, conectando o aprendizado teórico à prática diária do jogador.  
    - Ofereça sugestões de exercícios ou simulações que ajudem o jogador a internalizar os conceitos.  
    - Apresente as recomendações com um toque de leveza e bom humor, mantendo o jogador engajado e confiante de que está no caminho para dominar as mesas.  
    - Seja um guia prático e motivador, que faça o jogador sentir que aprender poker é tão divertido quanto ganhar um pote gigante (sem ter que mostrar as cartas!).  
    Ao final, o jogador terá um plano que é como um "GPS do poker" – com ele, chegar ao destino de ser um jogador lucrativo e imbatível será só questão de tempo (e algumas boas leituras entre as sessões).

generate_final_summary:

  description: >
    Criar um sumário executivo em formato markdown que sintetize as principais 
    informações geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara e objetiva 
    em uma página, facilitando o entendimento rápido do plano de desenvolvimento e direcionando o 
    colaborador para os documentos mais detalhados.

  expected_output: > 

    Um sumário executivo em markdown que sintetize as principais informações 
    geradas sobre o colaborador, incluindo diagnóstico inicial, ações educativas, 
    objetivos principais e cronograma. O objetivo é apresentar uma visão geral clara 
    e objetiva em uma página, facilitando o entendimento rápido do plano de desenvolvimento 
    e direcionando o colaborador para os documentos mais detalhados.